name: deploy
on:
  push:
    branches:
      - main 
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - name: Install mkdocs-turing-plugins
        run: |
          git clone https://github.com/deltaR-3k/mkdocs-turing-plugins.git
          cd mkdocs-turing-plugins
          pip install -e .
          cd ..
      - run: mkdocs gh-deploy --force